# Generated by Django 4.2.3 on 2023-07-27 13:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0003_alter_brand_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=199, unique=True),
        ),
    ]
